### ISSUE TITLE
Divide Dallas, Nashville and new locations

### ISSUE THREAD

**Issue by jamiewilson** [weld-co/telescope-theme-weld#19]
This will most likely need to be on the same instance, so that all members can access all posts without needing to create separate accounts.

Ideally welderwire.co/dallas, etc. So, there would be a header link that says Dallas  /  Nashville  /  Another Location. So that way each community can contribute and comment on the other, but content from each isn't intermingled. 

Probably needs to be created with custom views (http://www.telesc.pe/docs/adding-views/) but am not sure about auto adding tags to filter those views. All Dallas members' post should automatically be tagged with Dallas.

 It might make the most sense to have a default view off ALL Posts (most valuable for Ambassador members) and then get new users to pick a location to make that their default landing page.

**Comment by austinmann** [comment]
I feel it needs to be more apparent how to divide your feed between locations… maybe visible button in the side bar or something at the top of the feed. 

i know we talked in the past about defaulting to ALL but now wondering if it should default to the local, and give the secondary option to see all.

if it's not this, somehow we need to default to insulating not-related markets from the strictly local posts like requests for airport rides, announcements about building maintenance, etc…

**Comment by jamiewilson** [comment]
This issue was moved to weld-co/welderwire-theme#11
