### ISSUE TITLE
Add Comment placement

### ISSUE THREAD

**Issue by jordanbellamy** [weld-co/telescope-theme-weld#31]
“Add Comment” should come at the end of the page, after reading the other comments (I’ve found myself forgetting to scroll down, or even see that there are already comments) 

Everything should be on an infinite loop of: 
	⁃	Action 1: Read a post
	⁃	Action 2: Read the comments
	⁃	Action 3: Reply to the post and the comments
	⁃	Action 4: Go to next post (*eventually/hopefully without backtracking or clicking)

**Comment by jamiewilson** [comment]
This issue was moved to weld-co/welderwire-theme#30
