### ISSUE TITLE
WW: Events

### ISSUE THREAD

**Issue by austinmann** [weld-co/telescope-theme-weld#38]
## Urgency: Low

Sometimes people still use facebook to post events (like Whiskey Wednesday)… I think the compelling things about it are: 

* It asks the direct question: "are you going?" and allows you to opt-in
* Creates great "others are doing it" visibility 
* It consistently shows the when/where/why info in the same format (helps minimize confusion, better facilitates members doing their own things, etc) 

And of course it has push notifications. 

it seems like there could be a "I'm hosting an event" page or something. 

![Example Event Page]
(https://d1zjcuqflbd5k.cloudfront.net/files/acc_281934/156Ta?response-content-disposition=inline;%20filename=Screen%20Shot%20on%202015-03-17%20at%2020%3A46%3A05.png&Expires=1426643550&Signature=ebOFNQH~EG2C2Py0eXse2WQIP7wMEAnkMrq6eCvLNj9C6nOOl63~eFF8FvxsR2uZa~VbwqhUgdK5RYdSrmhSaibA0CjZWoT0EcdSr6WtQFpSGLqrq3EksMafikoOLXi17E5fzboJb-lC5V8FxZnl1LVJsa9Mp33pJIafAHYsF5k_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

**Comment by jamiewilson** [comment]
This issue was moved to weld-co/welderwire-theme#18
