### ISSUE TITLE
Command-Return to post comment

### ISSUE THREAD

**Issue by austinmann** [weld-co/telescope-theme-weld#39]
I always really appreciate it when I can complete a form w/ keyboard shortcut. 

Like to "Add Comment" on a conversation thread it would be awesome. (similar to what you did on the FormKeep stuff.)

**Comment by austinmann** [comment]
and exactly like what GitHub does, to post this very comment :-)

**Comment by austinmann** [comment]
is this possible? 

I still try to Command-Return every time I post a comment :-)

**Comment by jamiewilson** [comment]
Looks like someone has added this for the next release: https://trello.com/c/t3I4E50s/74-keyboard-shortcuts

**Comment by austinmann** [comment]
awesome! pumped for it to come out :-)

**Comment by jamiewilson** [comment]
This issue was moved to weld-co/welderwire-theme#19
