### ISSUE TITLE
Formal "Partners" Page inside WELDER Wire 

### ISSUE THREAD

**Issue by austinmann** [weld-co/telescope-theme-weld#42]
Make it really clear and easy to see the member deal: 

1) Who they are with 
2) How much $$ is saved 
3) Expectation of WELDERs that use it 
4) How to redeem it

**Comment by austinmann** [comment]
This is something I feel really needs to be done soon -- it adds so much value for us and our partners. Is there a timeline for implementing this?

**Comment by jamiewilson** [comment]
Sounds good. No timeline yet. Can you get me a list of all of our current deals with the related information listed above or point me in the direction of where to find it?

**Comment by austinmann** [comment]
the members.weld.co page had a great list on it. 

Nashville: 
None yet.

Dallas:
OakFit: 30% off For WELDERs
Redeem: Tell them you are a WELDER

BOLT: 15% off 
Redeem: Tell them you are a WELDER

Anyone: 
Kammok 50% off: WELD2015

MOO 10% off: Redeem here: http://us.moo.com/partner/weld-10/?utm_campaign=us_vertcre-cd_weld_partnerpage_10off_mar15&utm_medium=partner&utm_source=WELD+co

Blinksale: Free for WELDERs
Redeem: Sign up and email patrick@blinksale.com and tell him you are a WELDER

**Comment by jamiewilson** [comment]
Here's from the [old site](https://weldblog.squarespace.com/members):

- Moo -- 20% off (click for link)
- Kammok -- 50% off using code: WELD2014
- Squarespace -- 10% off using code: WELOVEWELD14
- Blinksale -- free (email patrick@blinksale.com to activate)
- Bolt Productions -- 15 - 20% off rentals (walk-in)
- Prnt Co -- up to 25% off (+ free sample kit for newbies) by emailing travis@prnt.co
- FoundersCard -- discounted membership rate (click link for perks)
- NEED -- 25% off (email hello@neededition.com to activate)

**Comment by jamiewilson** [comment]
This issue was moved to weld-co/welderwire-theme#20
