### ISSUE TITLE
WW: Hovering icon, remain grey

### ISSUE THREAD

**Issue by austinmann** [weld-co/telescope-theme-weld#43]
I have a theory that people don't "Like" posts as much because when you hover over it, it shows orange and "feels" like you have already liked. Can we change that so when you hover over the heart, it stays grey and feels like it's begging me to "like" it to make it orange?  

or is there another intentionality here that I'm not aware of?

**Comment by jamiewilson** [comment]
I think you're right. My initial thought was that hovering over the post, changing the Like color would draw attention to it, but it might be doing the opposite.

**Comment by jamiewilson** [comment]
Haven't pushed this live yet, but I removed the hover and now if you've upvoted or commented the respective icon and text will turn orange.

**Comment by austinmann** [comment]
awesome!
