### ISSUE TITLE
Share feature

### ISSUE THREAD

**Issue by austinmann** [weld-co/telescope-theme-weld#51]
Maybe add a button Share a Link w/ a friend would be great. 

1) Immediately, it could of fill the role of "@ mention" functionality, encouraging members to share content with other members (ie: hey did you see this @patrick? or "@patrick might have suggestions for this…" etc… ) 

I know that's not yet supported but the ability to click a button and easily send straight to Patrick would be huge. Especially for keeping users active and engaged on the platform. 

2) Future: It might be interesting if, as a non-logged in member, I could click this link and see the first part of the content (like NY times or LinkedIn.)

**Comment by jamiewilson** [comment]
This issue was moved to weld-co/welderwire-theme#25
