### ISSUE TITLE
Scaling issue

### ISSUE THREAD

**Issue by austinmann** [weld-co/telescope-theme-weld#55]
i think i posted this somewhere already but in Safari WELDER Wire hasn't been scrolling properly for a couple weeks.  

I see about four columns and then have to slide to right to see about 5-6 more columns.

**Comment by jamiewilson** [comment]
You talking about the /members page? Dang. i thought I fixed that. Taking a look now?

**Comment by austinmann** [comment]
Yea, the member directory: 
http://astn.mn/142I4

**Comment by austinmann** [comment]
this is fixed for me, looks awesome!

**Comment by jamiewilson** [comment]
:tada:
