### ISSUE TITLE
Sort to find users

### ISSUE THREAD

**Issue by austinmann** [weld-co/telescope-theme-weld#56]
Is it possible to organize these alphabetically so I can find a user?  

Skyler just told me he posted something to WELDER Wire, I want to see all his posts so I went to: 

welderwire.co > member directory >  sort by Dallas and then don't have a way of easily locating skyler.  

(I can do a search on the page (Command-F) for the word Skyler, and that's what works for now. ) 

SO, right now, if we can do alphabetical sorting, that would at least help. 

In the long run, I know we both want to be able to search to find users but just looking for something short term here.

**Comment by jamiewilson** [comment]
Alphabetical is on there, but ideally I could implement instant search or something.

**Comment by austinmann** [comment]
I think it should be alphabetical by default.

**Comment by jamiewilson** [comment]
Yeah, that can be changed. I felt like it was a bit more egalitarian to default to random.

**Comment by austinmann** [comment]
yea -- i definitely see that. i think the issue was that it wasn't clear how it was sorting… maybe we could do something in the middle where it's the newest users at the top or something? 

either way, i think it's stronger now as with a clearer intentionality. 

and yes, instant search would definitely be the preference whenever that could be built.
