### ISSUE TITLE
Simplify Picture Posting

### ISSUE THREAD

**Issue by austinmann** [weld-co/telescope-theme-weld#57]
It'd be awesome if it was possible to upload an image to a post (instead of markdown referencing an image on the web) but I assume it's not possible right now because of the same issues with profile pictures. 

So can we make it any clearer how to post a picture on WELDER wire for the time being? 
I actually still get confused myself and people here are trying to post them right now and not able.

**Comment by jamiewilson** [comment]
Yea. I'll try to make that clearer.

**Comment by jamiewilson** [comment]
This issue was moved to weld-co/welderwire-theme#27
