### ISSUE TITLE
Remove ID on Profile page

### ISSUE THREAD

**Issue by austinmann** [weld-co/telescope-theme-weld#58]
possible to remove the ID in the top left of the members page? 

birthday and date joined isnt too bad but the member ID feels too technical. 

http://astn.mn/1kJg0

**Comment by jamiewilson** [comment]
That's actually just for admins.

**Comment by austinmann** [comment]
ah yea, i think i knew that and forgot :-)

**Comment by jamiewilson** [comment]
:) no worries.
