### ISSUE TITLE
Scroll Bar in WW

### ISSUE THREAD

**Issue by austinmann** [weld-co/telescope-theme-weld#59]
something weird going on along the side bar… it's like it's a scroll bar or something

http://astn.mn/AqQC

**Comment by jamiewilson** [comment]
![screen shot 2015-05-11 at 15 00 03](https://cloud.githubusercontent.com/assets/3308673/7574743/42c3f832-f7f5-11e4-8bf0-be63aee8802b.png)

**Comment by jamiewilson** [comment]
Weird. I can reproduce this.

**Comment by jamiewilson** [comment]
Oh. Actually, this might not be something I can change depending on your settings here:

![screen shot 2015-05-11 at 3 53 18 pm](https://cloud.githubusercontent.com/assets/3308673/7574841/ebb3d566-f7f5-11e4-9a1b-95c1fa982944.png)

**Comment by austinmann** [comment]
yep - fixed on this end.
