### ISSUE TITLE
Emphasize Location Selection

### ISSUE THREAD

**Issue by austinmann** [weld-co/telescope-theme-weld#60]
love that you got this feature going -- it's going to be huge. 

i kind of feel it should be emphasized a bit more (to really make sure people get the best/relevant info and default to using it and we don't end up seeing dirty dishes 1000 miles away.) 

my thought is to create a section previous to "Categories" called "Location" or something like that, example here:
http://astn.mn/5HXM

**Comment by jamiewilson** [comment]
Yea. I agree. Would love to do it this way. Unfortunately I need to rewrite the whole post submit page along with some other backend things to make this work, so I was thinking about waiting until I refactor the whole app for this [big update to Telescope](http://www.telescopeapp.org/blog/previewing-telescope-big-refactor/).

**Comment by jamiewilson** [comment]
P.S. You can just drag and drop images into github and they'll host and display it inline:

![screen shot 2015-05-13 at 1 25 55 pm](https://cloud.githubusercontent.com/assets/3308673/7617862/9b672674-f973-11e4-9559-ae66ef705eb8.png)

**Comment by austinmann** [comment]
awesome. 

FYI, most of the time I assume we’re on same page on those types of things and that something bts has prevented it but I’m going to try to be better about voicing anyway. 

excited for that update to come!

**Comment by austinmann** [comment]
sweet. i kind of love the ability to draw stuff on it in Droplr… they came out with a new version of Droplr today that is pretty nice.

**Comment by jamiewilson** [comment]
This issue was moved to weld-co/welderwire-theme#28
