### ISSUE TITLE
Email Member on Profile page 

### ISSUE THREAD

**Issue by austinmann** [weld-co/telescope-theme-weld#62]
Until we can integrate @ mentions or some sort of direct messaging system between members, I really feel we need to make a main call to action on the profile page like "Email (name)" 

like this: 
http://astn.mn/1cqHm

for instance, I just read a post by David, and want to inquire with him directly… i click his name on the WW post and glance at his profile to contact him. Almost closed window but then realized his email was mixed into the social media handles.

**Comment by jamiewilson** [comment]
added this:

![screen shot 2015-06-25 at 5 49 55 pm](https://cloud.githubusercontent.com/assets/3308673/8367324/9d698e1a-1b62-11e5-981a-9277f9b678c9.png)
