### ISSUE TITLE
Return to feed after comment. 

### ISSUE THREAD

**Issue by austinmann** [weld-co/telescope-theme-weld#65]
Scenario: 

I post something to the WELDER Wire and get 8 comments.  I need to reply to more than one of them. Once I Reply to one comment, I have no clear way to get back to the rest of the conversation…  as far as I can tell, the quickest way is to click the WELD logo top left to return home, and then scroll back to my feed. 

Actually, just tried the back button, which I thought would take me to the previous page but it does take me back to where I need to be. 

Would love a way to more quickly/easily reply to a bunch of messages back and forth.

**Comment by jamiewilson** [comment]
It should now take you back to the post after replying to a comment.
