### ISSUE TITLE
Search isn't working

### ISSUE THREAD

**Issue by austinmann** [weld-co/telescope-theme-weld#66]
was trying to find our partner deals page that used to be sticky and when i try to search "limited" or "limited time" or "limited time partner"  I can't find it… it only shows the latest posts.

**Comment by jamiewilson** [comment]
weird. I just searched `limited` and it was the top result:
![screen shot 2015-06-26 at 11 03 53 am](https://cloud.githubusercontent.com/assets/3308673/8381712/117190f6-1bf3-11e5-86bd-b35f27301a16.png)

**Comment by jamiewilson** [comment]
This issue was moved to weld-co/welderwire-theme#32
